<?php
	$version="1.0";
	$time=time();
	$sonTime=@file_get_contents("../sonGuncellemeDenetleme.txt");
	if($sonTime+60*60*24<$time){
		$currentVersion=@file_get_contents("http://mcolak.net/colakMVC/currentVersion.txt");
		$dosya=fopen("../sonGuncellemeDenetleme.txt","w");
		fputs($dosya,time());
		fclose($dosya);
	}
	else{
		$currentVersion=$version;
	}
?>